sonar.projectKey=leopls07_pra-frente
sonar.organization=leopls07

sonar.sources=app/app,app/components,app/constants,app/services,app/store,app/types,app/utils,server/src

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/.expo/**,\
  **/android/**,\
  **/assets/**,\
  **/*.jks,\
  server/src/templates/**,\
  server/src/public/**

sonar.sourceEncoding=UTF-8
