sonar.projectKey=leopls07_pra-frente
sonar.organization=leopls07

sonar.sources=app/app,app/components,app/constants,app/services,app/store,app/types,app/utils,server/src

sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**

sonar.sourceEncoding=UTF-8
